### PR TITLE
Support a timeout on docker client.

### PR DESCRIPTION
**Pull request by dnephin**

### CODE REVIEW

**Comment by bfirsh** [comment]
@dnephin any chance you could open this upstream? we're seeing more interest for increasing the timeout as a stopgap for https://github.com/docker/fig/issues/812

/cc @simonvc @samphippen

**Comment by bfirsh** [comment]
cc @aanand

**Comment by dnephin** [comment]
@bfirsh  will do

**Comment by dnephin** [comment]
@bfirsh  actually, it looks like it's already upstream

**Comment by aanand** [comment]
Yep, merged a month ago - https://github.com/docker/fig/pull/720

**Comment by bfirsh** [comment]
Nice.

**Pull request merged**
